blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'
  devise_for :users
  get 'about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

blog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  # Active Storage Rails 5
  has_one_attached :thumbnail
  has_one_attached :banner
  # Action Text Rails 6
  has_rich_text :body

  validates :title, length: {minimum:5}
  validates :body, length: {minimum:25}

  def optimized_image(image,x,y)
    return image.variant(resize_to_fill: [x,y]).processed
  end
end

blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # aadvark@example.com ~> self.email.split('@') ~> ["aardvark", "example.com"] ~> [0] ~> "aardvark".capitalize ~> "Aardvark"
  def username
    return email.split('@')[0].capitalize
  end
end

  

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :is_admin!

    private
    def is_admin!
        if current_user && current_user.admin
        else
                redirect_to root_path
        end
    end
end

blog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :is_admin!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    views= @post.views + 1
    @post.update(views: views)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :thumbnail, :banner)
    end
end

blog/app/helpers/pages_helper.rb
module PagesHelper
end

blog/app/helpers/posts_helper.rb
module PostsHelper
end

blog/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

blog/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%= root_path %>">BLOG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= about_path %>">About</a>
        </li>

      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <% if current_user.admin %>
                    <a class="dropdown-item" href="#">New Post</a>
                    <% end %>
                    <a class="dropdown-item" href="<%= edit_user_registration_path %>">Account Settings</a>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", method: :delete %>
                </div>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path,class:'nav-link' %>
            </li>
        <% end %>
      </ul>
    </div>
  </nav>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

blog/app/views/pages/about.html.erb
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">About Me</h1>
        <div class="row">
            <p style="text-align: justify;">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim. Tristique risus nec feugiat in fermentum posuere urna. Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Hac habitasse platea dictumst quisque sagittis purus sit. Felis donec et odio pellentesque diam volutpat commodo sed. In fermentum et sollicitudin ac. Tempor orci dapibus ultrices in. Viverra adipiscing at in tellus integer. Lacus luctus accumsan tortor posuere ac ut consequat semper. Fermentum leo vel orci porta non pulvinar neque laoreet. Et odio pellentesque diam volutpat commodo. Enim ut sem viverra aliquet.
            <br/>
            <br/>
            Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum. Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Justo donec enim diam vulputate ut pharetra sit amet. Eleifend mi in nulla posuere. Hac habitasse platea dictumst quisque. Aliquet eget sit amet tellus. Ut lectus arcu bibendum at varius. Diam volutpat commodo sed egestas egestas. Eget velit aliquet sagittis id consectetur purus ut. Quis auctor elit sed vulputate mi sit amet mauris. Faucibus in ornare quam viverra orci sagittis. Ac ut consequat semper viverra nam libero justo laoreet sit. Dictum fusce ut placerat orci nulla pellentesque dignissim enim.
            </p>
            <hr class="my-4"/>
            <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" onclick="window.location.href = 'https://github.com/ahmadbadawikr';" class="btn btn-secondary">GitHub</button>
                <button type="button" onclick="window.location.href = 'https://instagram.com/ahmadbadawikr';" class="btn btn-secondary">Instagram</button>
                <button type="button" onclick="window.location.href = 'https://twitter.com/deadlineknight';" class="btn btn-secondary">Twitter</button>
            </div>
        </div>
    </div>
</div>

blog/app/views/posts/_form.html.erb
<%= form_with model:post do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.text_field :title, class:'form-control string' %>
    <%= f.label :thumbnail, class:'form-control' %>
    <%= f.file_field :thumbnail %>
    <%= f.label :banner, class:'form-control' %>
    <%= f.file_field :banner %>
    <%= f.rich_text_area :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

blog/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blog/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Views</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.views %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

blog/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

blog/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Views:</strong>
  <%= @post.views %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>